# Einführung in TensorFlow & NumPy

In [1]:
import tensorflow as tf
import numpy as np

Die folgende Übung soll Sie ein bisschen mit dem TensorFlow und NumPy package vertraut machen.<br>
Falls Sie eine Funktion oder Methode nachschauen wollen, können Sie im Vorschau Notebook oder direkt in der TensorFlow oder NumPy Doku nachschauen:

* TensorFlow: https://www.tensorflow.org/api_docs/python/tf/all_symbols
* NumPy: https://numpy.org/doc/stable/reference/generated/numpy.sum.html

### Überführen Sie folgende Tabelle in einen Tensor. Achten Sie dabei auf den geeigneten Datentyp

|    |   Artikel |   Menge |   Preis |
|---:|----------:|--------:|--------:|
|  0 |         0 |       5 |    6.52 |
|  1 |         1 |       2 |    4.3  |
|  2 |         2 |       3 |    2.15 |
|  3 |         3 |       4 |    1.75 |
|  4 |         4 |       1 |    0.5  |

In [2]:
liste = tf.constant([[0.,5.,6.52],[1.,2.,4.30],[2.,3.,2.15],[3.,4.,1.75],[4.,1.,0.5]])

In [3]:
liste

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.  , 5.  , 6.52],
       [1.  , 2.  , 4.3 ],
       [2.  , 3.  , 2.15],
       [3.  , 4.  , 1.75],
       [4.  , 1.  , 0.5 ]], dtype=float32)>

### Sie wollen nun den Gesamtumsatz aller Artikel Ihrer Liste berechnen. Nutzen Sie dafür entweder tensorflow oder numpy-Funktionalitäten

In [4]:
round(np.sum((liste[:,1] * liste[:,2]).numpy()),2)

55.15

### Ihr Preis ist nun um das doppelte gestiegen. Verrechnen Sie den Preisanstieg in Ihrem zuvor angelegten Tensor. Was ist nun das Problem?

In [5]:
liste[:,2]*2

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([13.04,  8.6 ,  4.3 ,  3.5 ,  1.  ], dtype=float32)>

In [6]:
liste[:,2] = liste[:,2]*2 ##nicht möglich, deswegen tf.Variable nötig

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [7]:
new_list = tf.Variable(liste)

In [8]:
new_list[:,2].assign(new_list[:,2]*2)

<tf.Variable 'UnreadVariable' shape=(5, 3) dtype=float32, numpy=
array([[ 0.  ,  5.  , 13.04],
       [ 1.  ,  2.  ,  8.6 ],
       [ 2.  ,  3.  ,  4.3 ],
       [ 3.  ,  4.  ,  3.5 ],
       [ 4.  ,  1.  ,  1.  ]], dtype=float32)>

In [9]:
new_list

<tf.Variable 'Variable:0' shape=(5, 3) dtype=float32, numpy=
array([[ 0.  ,  5.  , 13.04],
       [ 1.  ,  2.  ,  8.6 ],
       [ 2.  ,  3.  ,  4.3 ],
       [ 3.  ,  4.  ,  3.5 ],
       [ 4.  ,  1.  ,  1.  ]], dtype=float32)>